version: '3.3'

services:
  django:
    image: dockersky_image
    container_name: dockersky
    hostname: dockersky
    volumes:
      - dockersky_vol:/app
    ports:
      - "0:0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dockersky.com`)"
      - "traefik.http.routers.django.entrypoints=http,https"
      - "traefik.http.routers.django.tls.certresolver=http"
      - "traefik.http.routers.django.service=django"
      - "traefik.http.services.django.loadbalancer.server.port=0"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

volumes:
  dockersky_vol:
    external: true
